---

- name: Converge
  hosts: all
  gather_facts: true

  vars:
    ansible_python_interpreter: /usr/bin/python3

  roles:
    - role: iamenr0s.ansible_role_pkg_management
      vars:
        pkg_update_cache: true
        pkg_install:
          - tree
        pkg_upgrade: false
