---

- name: Verify
  hosts: all
  gather_facts: false

  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Assert tree package was installed
      ansible.builtin.assert:
        that:
          - "'tree' in ansible_facts.packages"
        fail_msg: "tree package was not installed by the role"
        success_msg: "tree package is installed"
